definition:
  openapi: 3.0.0
  info:
    title: Ecommerce API
    description: API project for learning
    version: 1.0.0
  servers:
    - url: http://localhost:3000
  components:
    schemas:
      User:
        type: object
        properties:
          id:
            type: number
          name:
            type: string
          email:
            type: string
          password:
            type: string
          phoneNumber:
            type: string
          role:
            type: string
        required:
          - name
          - email
          - password
          - role
      Asset:
        type: object
        properties:
          id:
            type: number
          owner:
            type: number
          originalUrl:
            type: string
          optimizedUrl:
            type: string
        required:
          - owner
          - originalUrl 
      Category:
        type: object
        properties:
          id:
            type: number
          name: 
            type: string
          slug:
            type: string
          description:
            type: string
          tags: 
            type: array
            items: 
              type: string
          asset:
            $ref:
              "#/components/schemas/Asset"
          products:
            type: array
            items:
              $ref:
                "#/components/schemas/Product"
        required:
          - name
          - slug
      Brand:
        type: object
        properties:
          name: 
            type: string
          description:
            type: string
          asset:
            $ref:
              "#/components/schemas/Asset"
          products:
            type: array
            items:
              $ref: 
                "#/components/schemas/Product"
        required:
          - name
      Attribute:
        type: object
        properties:
          id: 
            type: number
          name: 
            type: string
          value:
            type: string
        required:
          - name
          - value
      Variation:
        type: object
        properties:
          id:
            type: number
          productId:
            type: number
          assets:
            type: array
            items:
              $ref: 
                "#/components/schemas/Asset"
          attributes:
            type: array
            items:
              $ref:
                "#/components/schemas/Attribute"
          normalPrice:
            type: number
          offerPrice:
            type: number
          stock: 
            type: number
          isAvaible:
            type: boolean
        required:
          - productId
          - attributes
          - normalPrice
      Product:
        type: object
        properties:
          id:
            type: number
          name:
            type: string
          brandId:
            type: number
          categoryId:
            type: number
          description:
            type: string
          tags:
            type: array
            items:
              type: string
          asset:
            type: array
            items: 
              type: number
          variations:
            type: array
            items:
              $ref: 
                "#/components/schemas/Variation"
        required:
          - name
          - brandId
          - categoryId
  paths:
    #Users paths
    /api/v1/users:
      # list
      get:
        summary: Return all users
        responses:
          "200":
            description: A list of users.
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: 
                      "#/components/schemas/User"
      # create
      post:
        summary: Create a new User
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: 
                  "#components/schemas/User"
        responses:
          "201":
            description: User created
            content:
              application/json:
                schema:
                  $ref: 
                    "#components/schemas/User"
    /api/v1/users/{userId}:
      # retrieve
      get:
        summary: Return a user by ID
        parameters:
          - name: userId
            in: path
            required: true
            schema:
              type: integer
              format: int64
              minumin: 1
        responses:
          "200":
            description: User by ID
            content:
              application/json:
                schema:
                  $ref: 
                    "#components/schemas/User"
      # delete
      delete:
        summary: Delete a user by ID
        parameters:
          - name: userId
            in: path
            required: true
            schema:
              type: integer
              format: int64
              minumin: 1
        responses:
          "200":
            description: User deleted
            content:
              application/json:
                schema:
                  properties:
                    message:
                      type: string
                      example: "User deleted"
    /api/v1/users/{userId}/role:
      # update role
      patch:
        summary: Change user's role
        parameters:
          - name: userId
            in: path
            required: true
            schema:
              type: integer
              format: int64
              minumin: 1
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  role:
                    type: string
        responses:
          "200":
            description: User's role updated
            content:
              application/json:
                schema:
                  $ref: 
                    "#components/schemas/User"
    /api/v1/categories:
      get:
        summary: Get all categories
        responses:
          "200":
            description: List of categories
            content:
              application/json:
                schema:
                  $ref: 
                    "#/components/schemas/Category"
apis:
  - "./routes/*.js"
